FROM debian:stable-slim AS dnsmasq-builder

RUN dpkg --add-architecture armhf \
 && apt-get update \
 && apt-get -y install git make libc6-dev:armhf gcc-arm-linux-gnueabihf \
 && git clone -b master git://thekelleys.org.uk/dnsmasq.git /root/dnsmasq \
 && cd /root/dnsmasq/ \
 && CC=arm-linux-gnueabihf-gcc make install

FROM arm32v7/busybox:glibc

COPY --from=dnsmasq-builder /usr/local/sbin/dnsmasq /usr/sbin/dnsmasq

ENTRYPOINT [ "dnsmasq" ]
CMD [ "--help" ]
