FROM debian:stable-slim AS dnsmasq-builder

RUN dpkg --add-architecture arm64 \
 && apt-get update \
 && apt-get -y install git make libc6-dev:arm64 gcc-aarch64-linux-gnu \
 && git clone -b master git://thekelleys.org.uk/dnsmasq.git /root/dnsmasq \
 && cd /root/dnsmasq/ \
 && CC=aarch64-linux-gnu-gcc make install

FROM arm64v8/busybox:glibc

COPY --from=dnsmasq-builder /usr/local/sbin/dnsmasq /usr/sbin/dnsmasq

ENTRYPOINT [ "dnsmasq" ]
CMD [ "--help" ]
