FROM debian:9.8-slim AS dnsmasq-builder

RUN dpkg --add-architecture amd64 \
 && apt-get update \
 && apt-get -y install git make libc6-dev:amd64 gcc \
 && git clone -b v2.60 git://thekelleys.org.uk/dnsmasq.git /root/dnsmasq \
 && cd /root/dnsmasq/ \
 && CC=gcc make install

FROM amd64/busybox:glibc

COPY --from=dnsmasq-builder /usr/local/sbin/dnsmasq /usr/sbin/dnsmasq

ENTRYPOINT [ "dnsmasq" ]
CMD [ "--help" ]
