FROM debian:stable-slim AS dnsmasq-builder

RUN dpkg --add-architecture ppc64el \
 && apt-get update \
 && apt-get -y install git make libc6-dev:ppc64el gcc-powerpc64le-linux-gnu \
 && git clone -b master git://thekelleys.org.uk/dnsmasq.git /root/dnsmasq \
 && cd /root/dnsmasq/ \
 && CC=powerpc64le-linux-gnu-gcc make install

FROM ppc64le/busybox:glibc

COPY --from=dnsmasq-builder /usr/local/sbin/dnsmasq /usr/sbin/dnsmasq

ENTRYPOINT [ "dnsmasq" ]
CMD [ "--help" ]
