FROM debian:stable-slim AS dnsmasq-builder

RUN dpkg --add-architecture armel \
 && apt-get update \
 && apt-get -y install git make libc6-dev:armel gcc-arm-linux-gnueabi \
 && git clone -b master git://thekelleys.org.uk/dnsmasq.git /root/dnsmasq \
 && cd /root/dnsmasq/ \
 && CC=arm-linux-gnueabi-gcc make install

FROM arm32v5/busybox:glibc

COPY --from=dnsmasq-builder /usr/local/sbin/dnsmasq /usr/sbin/dnsmasq

ENTRYPOINT [ "dnsmasq" ]
CMD [ "--help" ]
